- become: yes
  hosts: localhost
  name: pre-install

  tasks:
    - name: Retrieve docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
    - name: Retrieve Jenkins repo
      command: '{{ item }}'
      loop:
        - yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    - name: Install Dependency packages
      yum:
        name: '{{ item }}'
        state: present
        update_cache: True
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - java-1.8.0-openjdk-devel
        - jenkins
        - git
        - curl
        - unzip
    - name: Enable the docker and jenkins services
      command: systemctl enable "{{ item }}"
      loop:
        - docker
        - jenkins
    - name: Start docker and jenkins services
      command: systemctl start "{{ item }}"
      loop:
        - docker
        - jenkins
    - name: Add the user 'jenkins' and add it to 'sudo' and docker
      user:
        name: jenkins
        group: docker
    - name: Download jq binary
      get_url:
        url: https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
        dest: /home/centos
    - name: Move the Binary
      command: '{{ item }}'
      loop:
        - mv /home/centos/jq-linux64 /usr/bin/jq
        - chmod +x /usr/bin/jq
    - name: Download SonarQube docker-compose.yml
      get_url:
        url: https://raw.githubusercontent.com/kodekolli/eks-demo-project/main/docker-compose.yml
        dest: /home/centos
    - name: Install SonarQube Server
      command: '{{ item }}'
      loop:        
        - sysctl -w vm.max_map_count=262144
        - sysctl -w fs.file-max=65536
        - docker-compose -f /home/centos/docker-compose.yml up -d
        - sleep 5
        - chmod -R 777 /data
        - pip3 install openshift
    - name: Install pyarmor
      command: pip3 install pyarmor
    - name: Trivy Installation
      command: '{{ item }}'
      loop:
        - rpm -ivh https://github.com/aquasecurity/trivy/releases/download/v0.18.1/trivy_0.18.1_Linux-64bit.rpm
        - mv /usr/local/bin/trivy /usr/bin
